[2024-03-23T18:14:03.036+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_bigquery.create_table scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-03-23T18:14:03.047+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_bigquery.create_table scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-03-23T18:14:03.048+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-23T18:14:03.068+0000] {taskinstance.py:2191} INFO - Executing <Task(BigQueryCreateEmptyTableOperator): create_table> on 2024-03-22 00:00:00+00:00
[2024-03-23T18:14:03.075+0000] {standard_task_runner.py:60} INFO - Started process 6015 to run task
[2024-03-23T18:14:03.078+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_bigquery', 'create_table', 'scheduled__2024-03-22T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpdya0ohgm']
[2024-03-23T18:14:03.081+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask create_table
[2024-03-23T18:14:03.142+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_bigquery.create_table scheduled__2024-03-22T00:00:00+00:00 [running]> on host 8a685a05c3f5
[2024-03-23T18:14:03.244+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhduc' AIRFLOW_CTX_DAG_ID='etl_to_bigquery' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-22T00:00:00+00:00'
[2024-03-23T18:14:03.256+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-23T18:14:03.257+0000] {base.py:83} INFO - Using connection ID 'gcp' for task execution.
[2024-03-23T18:14:03.258+0000] {bigquery.py:1412} INFO - Creating table
[2024-03-23T18:14:04.883+0000] {bigquery.py:1440} INFO - Table retail.raw_invoices already exists.
[2024-03-23T18:14:04.941+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_to_bigquery, task_id=create_table, execution_date=20240322T000000, start_date=20240323T181403, end_date=20240323T181404
[2024-03-23T18:14:04.986+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-23T18:14:05.023+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
