[2024-03-25T15:57:36.066+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_bigquery.create_retail_dataset manual__2024-03-25T08:55:15.952824+00:00 [queued]>
[2024-03-25T15:57:36.079+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_bigquery.create_retail_dataset manual__2024-03-25T08:55:15.952824+00:00 [queued]>
[2024-03-25T15:57:36.080+0700] {taskinstance.py:2170} INFO - Starting attempt 4 of 5
[2024-03-25T15:57:36.099+0700] {taskinstance.py:2191} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_retail_dataset> on 2024-03-25 08:55:15.952824+00:00
[2024-03-25T15:57:36.109+0700] {standard_task_runner.py:60} INFO - Started process 472 to run task
[2024-03-25T15:57:36.112+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_bigquery', 'create_retail_dataset', 'manual__2024-03-25T08:55:15.952824+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpdl5z3v9v']
[2024-03-25T15:57:36.115+0700] {standard_task_runner.py:88} INFO - Job 17: Subtask create_retail_dataset
[2024-03-25T15:57:36.164+0700] {task_command.py:423} INFO - Running <TaskInstance: etl_to_bigquery.create_retail_dataset manual__2024-03-25T08:55:15.952824+00:00 [running]> on host b24fc08bdd37
[2024-03-25T15:57:36.262+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhduc' AIRFLOW_CTX_DAG_ID='etl_to_bigquery' AIRFLOW_CTX_TASK_ID='create_retail_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T08:55:15.952824+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T08:55:15.952824+00:00'
[2024-03-25T15:57:36.273+0700] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-25T15:57:36.274+0700] {base.py:83} INFO - Using connection ID 'gcp' for task execution.
[2024-03-25T15:57:36.275+0700] {bigquery.py:468} INFO - datasetId was not specified in `dataset_reference`. Will use default value retail.
[2024-03-25T15:57:36.276+0700] {bigquery.py:468} INFO - projectId was not specified in `dataset_reference`. Will use default value steady-monitor-415517.
[2024-03-25T15:57:36.277+0700] {bigquery.py:479} INFO - Creating dataset: retail in project: steady-monitor-415517 
[2024-03-25T15:57:38.056+0700] {bigquery.py:1932} INFO - Dataset retail already exists.
[2024-03-25T15:57:38.099+0700] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_to_bigquery, task_id=create_retail_dataset, execution_date=20240325T085515, start_date=20240325T085736, end_date=20240325T085738
[2024-03-25T15:57:38.172+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-25T15:57:38.207+0700] {taskinstance.py:3280} INFO - 2 downstream tasks scheduled from follow-on schedule check
